name: Publish to npm

on:
  workflow_dispatch:
    inputs:
      package:
        description: 'Which package to publish?'
        required: true
        type: choice
        default: itwinui-css
        options:
          - itwinui-css
          - itwinui-variables
      tag:
        description: 'Which npm tag to publish to?'
        required: true
        type: choice
        default: latest
        options:
          - latest
          - dev

jobs:
  publish:
    name: Build and publish output to npm
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Use Node 16.X
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
          registry-url: https://registry.npmjs.org/

      - run: yarn install
      - run: yarn build --filter=${{ inputs.package }}

      - run: npm publish --access public --tag ${{ inputs.tag }}
        working-directory: './packages/${{ inputs.package }}/'
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPMJS_PUBLISH_ITWIN }}
